[DEBUG  ][03 Nov 2015 18:23:00][MainWindow.py:49] connect success
[DEBUG  ][03 Nov 2015 18:23:39][TcpClient.py:41] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 18:23:39][TcpClient.py:82] tcp client stopped
[ERROR  ][03 Nov 2015 18:25:39][TcpClient.py:31] connect exp: timed out
[ERROR  ][03 Nov 2015 18:25:39][MainWindow.py:53] connect error
[ERROR  ][03 Nov 2015 18:25:49][TcpClient.py:31] connect exp: 
[ERROR  ][03 Nov 2015 18:25:49][MainWindow.py:53] connect error
[ERROR  ][03 Nov 2015 18:25:54][TcpClient.py:31] connect exp: 
[ERROR  ][03 Nov 2015 18:25:54][MainWindow.py:53] connect error
[ERROR  ][03 Nov 2015 18:26:07][TcpClient.py:31] connect exp: 
[ERROR  ][03 Nov 2015 18:26:07][MainWindow.py:53] connect error
[DEBUG  ][03 Nov 2015 18:26:17][MainWindow.py:49] connect success
[DEBUG  ][03 Nov 2015 18:26:41][TcpClient.py:41] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 18:26:41][TcpClient.py:82] tcp client stopped
[DEBUG  ][03 Nov 2015 18:28:47][MainWindow.py:49] connect success
[DEBUG  ][03 Nov 2015 18:28:52][TcpClient.py:41] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 18:28:52][TcpClient.py:82] tcp client stopped
[DEBUG  ][03 Nov 2015 18:29:08][MainWindow.py:49] connect success
[DEBUG  ][03 Nov 2015 18:29:41][TcpClient.py:41] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 18:29:41][TcpClient.py:82] tcp client stopped
[DEBUG  ][03 Nov 2015 18:35:05][MainWindow.py:49] connect success
[DEBUG  ][03 Nov 2015 18:35:13][MainWindowPresenter.py:34] stop scan
[DEBUG  ][03 Nov 2015 18:35:16][TcpClient.py:41] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 18:35:16][TcpClient.py:82] tcp client stopped
[DEBUG  ][03 Nov 2015 18:35:49][MainWindow.py:49] connect success
[DEBUG  ][03 Nov 2015 18:35:54][MainWindowPresenter.py:34] stop scan
[DEBUG  ][03 Nov 2015 18:35:54][MainWindowPresenter.py:41]  
  0000: 06 00 08 01 12 02 08 03                          ........

[DEBUG  ][03 Nov 2015 18:36:07][MainWindowPresenter.py:37] start scan
[DEBUG  ][03 Nov 2015 18:36:07][MainWindowPresenter.py:41]  
  0000: 06 00 08 01 12 02 08 02                          ........

[DEBUG  ][03 Nov 2015 18:36:10][TcpClient.py:41] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 18:36:10][TcpClient.py:82] tcp client stopped
[DEBUG  ][03 Nov 2015 18:39:46][MainWindow.py:56] connect success
[DEBUG  ][03 Nov 2015 18:39:51][MainWindowPresenter.py:34] stop scan
[DEBUG  ][03 Nov 2015 18:39:51][MainWindowPresenter.py:41]  
  0000: 06 00 08 01 12 02 08 03                          ........

[DEBUG  ][03 Nov 2015 18:39:58][MainWindowPresenter.py:34] stop scan
[DEBUG  ][03 Nov 2015 18:39:58][MainWindowPresenter.py:41]  
  0000: 06 00 08 01 12 02 08 03                          ........

[DEBUG  ][03 Nov 2015 18:40:10][MainWindowPresenter.py:37] start scan
[DEBUG  ][03 Nov 2015 18:40:10][MainWindowPresenter.py:41]  
  0000: 06 00 08 01 12 02 08 02                          ........

[DEBUG  ][03 Nov 2015 18:40:13][MainWindowPresenter.py:34] stop scan
[DEBUG  ][03 Nov 2015 18:40:13][MainWindowPresenter.py:41]  
  0000: 06 00 08 01 12 02 08 03                          ........

[DEBUG  ][03 Nov 2015 18:40:14][MainWindowPresenter.py:34] stop scan
[DEBUG  ][03 Nov 2015 18:40:14][MainWindowPresenter.py:41]  
  0000: 06 00 08 01 12 02 08 03                          ........

[DEBUG  ][03 Nov 2015 18:40:18][MainWindowPresenter.py:37] start scan
[DEBUG  ][03 Nov 2015 18:40:18][MainWindowPresenter.py:41]  
  0000: 06 00 08 01 12 02 08 02                          ........

[DEBUG  ][03 Nov 2015 18:40:24][MainWindowPresenter.py:34] stop scan
[DEBUG  ][03 Nov 2015 18:40:24][MainWindowPresenter.py:41]  
  0000: 06 00 08 01 12 02 08 03                          ........

[DEBUG  ][03 Nov 2015 18:40:36][MainWindowPresenter.py:37] start scan
[DEBUG  ][03 Nov 2015 18:40:36][MainWindowPresenter.py:41]  
  0000: 06 00 08 01 12 02 08 02                          ........

[DEBUG  ][03 Nov 2015 18:40:45][MainWindowPresenter.py:34] stop scan
[DEBUG  ][03 Nov 2015 18:40:45][MainWindowPresenter.py:41]  
  0000: 06 00 08 01 12 02 08 03                          ........

[DEBUG  ][03 Nov 2015 18:40:50][TcpClient.py:41] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 18:40:50][TcpClient.py:82] tcp client stopped
[DEBUG  ][03 Nov 2015 18:42:03][MainWindow.py:56] connect success
[DEBUG  ][03 Nov 2015 18:42:15][TcpClient.py:41] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 18:42:15][TcpClient.py:82] tcp client stopped
[ERROR  ][03 Nov 2015 18:42:38][TcpClient.py:31] connect exp: timed out
[ERROR  ][03 Nov 2015 18:42:38][MainWindow.py:60] connect error
[ERROR  ][03 Nov 2015 18:42:46][TcpClient.py:31] connect exp: 
[ERROR  ][03 Nov 2015 18:42:46][MainWindow.py:60] connect error
[DEBUG  ][03 Nov 2015 18:42:52][MainWindow.py:56] connect success
[DEBUG  ][03 Nov 2015 18:43:06][TcpClient.py:41] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 18:43:06][TcpClient.py:82] tcp client stopped
[DEBUG  ][03 Nov 2015 18:43:21][MainWindow.py:56] connect success
[DEBUG  ][03 Nov 2015 18:43:29][TcpClient.py:41] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 18:43:29][TcpClient.py:82] tcp client stopped
[DEBUG  ][03 Nov 2015 18:43:46][MainWindow.py:56] connect success
[DEBUG  ][03 Nov 2015 18:43:57][TcpClient.py:41] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 18:43:57][TcpClient.py:82] tcp client stopped
[DEBUG  ][03 Nov 2015 18:44:32][MainWindow.py:56] connect success
[DEBUG  ][03 Nov 2015 18:44:58][TcpClient.py:41] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 18:44:58][TcpClient.py:82] tcp client stopped
[DEBUG  ][03 Nov 2015 18:45:11][MainWindow.py:56] connect success
[DEBUG  ][03 Nov 2015 18:45:50][TcpClient.py:41] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 18:45:50][TcpClient.py:82] tcp client stopped
[DEBUG  ][03 Nov 2015 18:46:33][MainWindow.py:53] connect success
[DEBUG  ][03 Nov 2015 18:46:55][TcpClient.py:41] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 18:46:55][TcpClient.py:82] tcp client stopped
[DEBUG  ][03 Nov 2015 18:48:28][MainWindow.py:53] connect success
[DEBUG  ][03 Nov 2015 18:48:43][TcpClient.py:41] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 18:48:43][TcpClient.py:82] tcp client stopped
[DEBUG  ][03 Nov 2015 18:52:43][MainWindow.py:57] connect success
[DEBUG  ][03 Nov 2015 18:52:45][TcpClient.py:45] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 18:52:45][TcpClient.py:87] tcp client stopped
[ERROR  ][03 Nov 2015 18:52:54][TcpClient.py:35] connect exp: 'TcpClient' object has no attribute 'createSockByType'
[ERROR  ][03 Nov 2015 18:52:54][MainWindow.py:60] connect error
[ERROR  ][03 Nov 2015 18:53:10][TcpClient.py:35] connect exp: 'TcpClient' object has no attribute 'createSockByType'
[ERROR  ][03 Nov 2015 18:53:10][MainWindow.py:60] connect error
[DEBUG  ][03 Nov 2015 18:54:05][MainWindow.py:57] connect success
[DEBUG  ][03 Nov 2015 18:54:26][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 18:54:26][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 18:55:22][MainWindow.py:57] connect success
[DEBUG  ][03 Nov 2015 18:55:24][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 18:55:24][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 18:55:26][MainWindow.py:57] connect success
[DEBUG  ][03 Nov 2015 18:55:36][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 18:55:36][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 18:56:40][MainWindow.py:58] connect success
[DEBUG  ][03 Nov 2015 18:56:46][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 18:56:46][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 18:56:48][MainWindow.py:58] connect success
[DEBUG  ][03 Nov 2015 18:56:52][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 18:56:52][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 18:58:15][MainWindow.py:58] connect success
[DEBUG  ][03 Nov 2015 18:58:19][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 18:58:19][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 18:58:21][MainWindow.py:58] connect success
[DEBUG  ][03 Nov 2015 18:58:40][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 18:58:40][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 18:58:43][MainWindow.py:58] connect success
[DEBUG  ][03 Nov 2015 18:58:49][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 18:58:49][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 18:58:52][MainWindow.py:58] connect success
[DEBUG  ][03 Nov 2015 18:58:57][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 18:58:57][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 18:59:00][MainWindow.py:58] connect success
[DEBUG  ][03 Nov 2015 18:59:51][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 18:59:51][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 19:01:14][MainWindow.py:58] connect success
[DEBUG  ][03 Nov 2015 19:01:17][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 19:01:17][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 19:01:32][MainWindow.py:58] connect success
[DEBUG  ][03 Nov 2015 19:01:35][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 19:01:35][TcpClient.py:86] tcp client stopped
[ERROR  ][03 Nov 2015 19:01:56][TcpClient.py:34] connect exp: timed out
[ERROR  ][03 Nov 2015 19:01:56][MainWindow.py:62] connect error
[ERROR  ][03 Nov 2015 19:02:00][TcpClient.py:34] connect exp: 
[ERROR  ][03 Nov 2015 19:02:00][MainWindow.py:62] connect error
[ERROR  ][03 Nov 2015 19:02:11][TcpClient.py:34] connect exp: 
[ERROR  ][03 Nov 2015 19:02:11][MainWindow.py:62] connect error
[DEBUG  ][03 Nov 2015 19:02:20][MainWindow.py:58] connect success
[DEBUG  ][03 Nov 2015 19:02:23][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 19:02:23][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 19:02:25][MainWindow.py:58] connect success
[DEBUG  ][03 Nov 2015 19:02:27][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 19:02:27][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 19:02:29][MainWindow.py:58] connect success
[DEBUG  ][03 Nov 2015 19:02:32][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 19:02:32][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 19:02:34][MainWindow.py:58] connect success
[DEBUG  ][03 Nov 2015 19:02:38][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 19:02:38][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 19:02:39][MainWindow.py:58] connect success
[DEBUG  ][03 Nov 2015 19:02:42][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 19:02:42][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 19:02:46][MainWindow.py:58] connect success
[DEBUG  ][03 Nov 2015 19:03:07][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 19:03:07][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 19:03:10][MainWindow.py:58] connect success
[DEBUG  ][03 Nov 2015 19:03:11][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 19:03:11][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 19:04:11][MainWindow.py:58] connect success
[DEBUG  ][03 Nov 2015 19:04:15][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 19:04:15][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 19:16:25][MainWindow.py:62] connect success
[DEBUG  ][03 Nov 2015 19:16:27][MainWindow.py:51] connect to ble device: 74:DA:EA:AE:9A:33
[DEBUG  ][03 Nov 2015 19:16:30][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 19:16:30][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 19:20:56][MainWindow.py:62] connect success
[DEBUG  ][03 Nov 2015 19:21:00][MainWindow.py:51] connect to ble device: 74:DA:EA:AE:9A:33
[DEBUG  ][03 Nov 2015 19:21:02][MainWindow.py:51] connect to ble device: 88:0F:10:74:C7:C5
[DEBUG  ][03 Nov 2015 19:21:03][MainWindow.py:51] connect to ble device: E0:C6:70:31:F7:6C
[DEBUG  ][03 Nov 2015 19:21:03][MainWindow.py:51] connect to ble device: 88:0F:10:74:C7:C5
[DEBUG  ][03 Nov 2015 19:21:04][MainWindow.py:51] connect to ble device: E0:C6:70:31:F7:6C
[DEBUG  ][03 Nov 2015 19:21:04][MainWindow.py:51] connect to ble device: 74:DA:EA:AE:9A:33
[DEBUG  ][03 Nov 2015 19:21:06][MainWindow.py:51] connect to ble device: 74:DA:EA:AE:9A:33
[DEBUG  ][03 Nov 2015 19:21:06][MainWindow.py:51] connect to ble device: E0:C6:70:31:F7:6C
[DEBUG  ][03 Nov 2015 19:21:07][MainWindow.py:51] connect to ble device: 88:0F:10:74:C7:C5
[DEBUG  ][03 Nov 2015 19:21:07][MainWindow.py:51] connect to ble device: E0:C6:70:31:F7:6C
[DEBUG  ][03 Nov 2015 19:21:08][MainWindow.py:51] connect to ble device: 74:DA:EA:AE:9A:33
[DEBUG  ][03 Nov 2015 19:21:08][MainWindow.py:51] connect to ble device: E0:C6:70:31:F7:6C
[DEBUG  ][03 Nov 2015 19:21:09][MainWindow.py:51] connect to ble device: 88:0F:10:74:C7:C5
[DEBUG  ][03 Nov 2015 19:21:26][MainWindow.py:51] connect to ble device: E0:C6:70:31:F7:6C
[DEBUG  ][03 Nov 2015 19:21:26][MainWindow.py:51] connect to ble device: 88:0F:10:74:C7:C5
[DEBUG  ][03 Nov 2015 19:21:27][MainWindow.py:51] connect to ble device: D5:EB:02:3F:7C:5A
[DEBUG  ][03 Nov 2015 19:21:27][MainWindow.py:51] connect to ble device: 88:0F:10:74:C7:C5
[DEBUG  ][03 Nov 2015 19:21:28][MainWindow.py:51] connect to ble device: E0:C6:70:31:F7:6C
[DEBUG  ][03 Nov 2015 19:21:28][MainWindow.py:51] connect to ble device: 74:DA:EA:AE:9A:33
[DEBUG  ][03 Nov 2015 19:21:30][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 19:21:30][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 19:26:11][MainWindow.py:64] connect success
[DEBUG  ][03 Nov 2015 19:26:14][MainWindow.py:51] connect to ble device: 74:DA:EA:AE:9A:33
[DEBUG  ][03 Nov 2015 19:26:48][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 19:26:48][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 19:27:09][MainWindow.py:64] connect success
[DEBUG  ][03 Nov 2015 19:27:11][MainWindow.py:51] connect to ble device: 74:DA:EA:AE:9A:33
[DEBUG  ][03 Nov 2015 19:27:22][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 19:27:22][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 19:34:52][MainWindow.py:72] connect success
[DEBUG  ][03 Nov 2015 19:34:56][MainWindow.py:51] connect to ble device: 74:DA:EA:AE:9A:33
[DEBUG  ][03 Nov 2015 19:35:08][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 19:35:08][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 19:35:42][MainWindow.py:72] connect success
[DEBUG  ][03 Nov 2015 19:35:45][MainWindow.py:51] connect to ble device: 88:0F:10:74:C7:C5
[DEBUG  ][03 Nov 2015 19:36:05][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 19:36:05][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 19:42:30][MainWindow.py:65] connect success
[DEBUG  ][03 Nov 2015 19:42:32][MainWindow.py:52] connect to ble device: 74:DA:EA:AE:9A:33
[DEBUG  ][03 Nov 2015 19:42:34][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 19:42:34][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 19:43:09][MainWindow.py:65] connect success
[DEBUG  ][03 Nov 2015 19:43:12][MainWindow.py:52] connect to ble device: E0:C6:70:31:F7:6C
[DEBUG  ][03 Nov 2015 19:43:13][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 19:43:13][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 19:43:27][MainWindow.py:65] connect success
[DEBUG  ][03 Nov 2015 19:43:28][MainWindow.py:52] connect to ble device: E0:C6:70:31:F7:6C
[DEBUG  ][03 Nov 2015 19:44:24][MainWindow.py:65] connect success
[DEBUG  ][03 Nov 2015 19:44:27][MainWindow.py:52] connect to ble device: 74:DA:EA:AE:9A:33
[DEBUG  ][03 Nov 2015 19:44:31][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 19:44:31][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 19:52:14][MainWindow.py:65] connect success
[DEBUG  ][03 Nov 2015 19:52:16][MainWindow.py:52] connect to ble device: 74:DA:EA:AE:9A:33
[DEBUG  ][03 Nov 2015 19:53:14][MainWindow.py:65] connect success
[DEBUG  ][03 Nov 2015 19:53:15][MainWindow.py:52] connect to ble device: E0:C6:70:31:F7:6C
[DEBUG  ][03 Nov 2015 19:53:36][MainWindow.py:65] connect success
[DEBUG  ][03 Nov 2015 19:53:38][MainWindow.py:52] connect to ble device: 74:DA:EA:AE:9A:33
[DEBUG  ][03 Nov 2015 19:55:13][MainWindow.py:65] connect success
[DEBUG  ][03 Nov 2015 19:55:15][MainWindow.py:52] connect to ble device: 74:DA:EA:AE:9A:33
[DEBUG  ][03 Nov 2015 19:56:44][MainWindow.py:65] connect success
[DEBUG  ][03 Nov 2015 19:56:45][MainWindow.py:52] connect to ble device: 74:DA:EA:AE:9A:33
[DEBUG  ][03 Nov 2015 19:56:55][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 19:56:55][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 19:57:08][MainWindow.py:65] connect success
[DEBUG  ][03 Nov 2015 19:57:09][MainWindow.py:52] connect to ble device: 74:DA:EA:AE:9A:33
[DEBUG  ][03 Nov 2015 19:57:14][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 19:57:14][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 19:58:13][MainWindow.py:65] connect success
[DEBUG  ][03 Nov 2015 19:58:14][MainWindow.py:52] connect to ble device: 74:DA:EA:AE:9A:33
[DEBUG  ][03 Nov 2015 19:58:19][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 19:58:19][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 19:58:58][MainWindow.py:65] connect success
[DEBUG  ][03 Nov 2015 19:59:00][MainWindow.py:52] connect to ble device: 74:DA:EA:AE:9A:33
[DEBUG  ][03 Nov 2015 19:59:05][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 19:59:05][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 20:01:15][MainWindow.py:65] connect success
[DEBUG  ][03 Nov 2015 20:01:16][MainWindow.py:52] connect to ble device: E0:C6:70:31:F7:6C
[DEBUG  ][03 Nov 2015 20:01:18][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 20:01:18][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 20:02:19][MainWindow.py:65] connect success
[DEBUG  ][03 Nov 2015 20:02:20][MainWindow.py:52] connect to ble device: 74:DA:EA:AE:9A:33
[DEBUG  ][03 Nov 2015 20:02:25][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 20:02:25][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 20:04:01][MainWindow.py:65] connect success
[DEBUG  ][03 Nov 2015 20:04:02][MainWindow.py:52] connect to ble device: 74:DA:EA:AE:9A:33
[DEBUG  ][03 Nov 2015 20:04:08][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 20:04:08][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 20:05:18][MainWindow.py:65] connect success
[DEBUG  ][03 Nov 2015 20:05:19][MainWindow.py:52] connect to ble device: 74:DA:EA:AE:9A:33
[DEBUG  ][03 Nov 2015 20:05:24][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 20:05:24][TcpClient.py:86] tcp client stopped
[ERROR  ][03 Nov 2015 20:06:33][TcpClient.py:34] connect exp: timed out
[ERROR  ][03 Nov 2015 20:06:33][MainWindow.py:69] connect error
[ERROR  ][03 Nov 2015 20:06:37][TcpClient.py:34] connect exp: 
[ERROR  ][03 Nov 2015 20:06:37][MainWindow.py:69] connect error
[DEBUG  ][03 Nov 2015 20:06:42][MainWindow.py:65] connect success
[DEBUG  ][03 Nov 2015 20:06:45][MainWindow.py:52] connect to ble device: 74:DA:EA:AE:9A:33
[DEBUG  ][03 Nov 2015 20:06:50][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 20:06:50][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 20:08:22][MainWindow.py:65] connect success
[DEBUG  ][03 Nov 2015 20:08:25][MainWindow.py:52] connect to ble device: 88:0F:10:74:C7:C5
[DEBUG  ][03 Nov 2015 20:08:36][MainWindow.py:52] connect to ble device: 88:0F:10:74:C7:C5
[DEBUG  ][03 Nov 2015 20:08:38][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 20:08:38][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 20:09:48][MainWindow.py:65] connect success
[DEBUG  ][03 Nov 2015 20:09:50][MainWindow.py:52] connect to ble device: 74:DA:EA:AE:9A:33
[DEBUG  ][03 Nov 2015 20:09:54][MainWindow.py:52] connect to ble device: CC:36:6A:4A:32:F8
[DEBUG  ][03 Nov 2015 20:09:57][MainWindow.py:52] connect to ble device: E0:C6:70:31:F7:6C
[DEBUG  ][03 Nov 2015 20:10:04][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 20:10:04][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 20:10:20][MainWindow.py:65] connect success
[DEBUG  ][03 Nov 2015 20:10:21][MainWindow.py:52] connect to ble device: 74:DA:EA:AE:9A:33
[DEBUG  ][03 Nov 2015 20:10:25][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 20:10:25][TcpClient.py:86] tcp client stopped
[DEBUG  ][03 Nov 2015 20:10:52][MainWindow.py:65] connect success
[DEBUG  ][03 Nov 2015 20:10:53][MainWindow.py:52] connect to ble device: 74:DA:EA:AE:9A:33
[DEBUG  ][03 Nov 2015 20:10:56][MainWindow.py:52] connect to ble device: E0:C6:70:31:F7:6C
[DEBUG  ][03 Nov 2015 20:10:57][MainWindow.py:52] connect to ble device: CC:36:6A:4A:32:F8
[DEBUG  ][03 Nov 2015 20:11:00][TcpClient.py:44] ------ CLOSE ------
[DEBUG  ][03 Nov 2015 20:11:00][TcpClient.py:86] tcp client stopped
